/* Cabin data — Birken Lakeside Resort */
window.CABINS = [
  {
    id: 'wild-west',
    name: 'Wild West',
    tag: 'Historic log cabin. Lakeside.',
    blurb: 'A real 1906 log cabin on the lake. Wood stove, planked floors, kettle on the boil. The oldest soul on the property.',
    type: 'Cabin',
    sleeps: 4,
    beds: '1 Queen + 1 Sofa',
    bath: 'Private',
    price: 375,
    ext: 'assets/wildwest-ext.jpeg',
    int: 'assets/wildwest-int.jpeg',
    features: ['Wood stove', 'Lake view', 'Full kitchen', 'Original 1906 logs', 'Front porch', 'Pet friendly'],
  },
  {
    id: 'morocco',
    name: 'Morocco',
    eyebrow: 'The Cosy Gem',
    tag: 'Our smallest, our most rustic, our highest on charm.',
    blurb: 'Brass lanterns, woven headboard. The smallest cabin with the loudest personality.',
    type: 'Cabin',
    sleeps: 2,
    beds: '1 Queen',
    bath: 'Shared',
    price: 145,
    ext: 'assets/morocco-cabin-night.jpeg',
    int: 'assets/morocco-lantern.jpeg',
    features: ['Themed interior', 'Reading nook', 'Kitchenette', 'Localised heating'],
  },
  {
    id: 'mexico',
    name: 'Mexico',
    eyebrow: 'Festive Escape',
    tag: 'A covered porch, a private firepit, and a Spanish-style soul.',
    blurb: 'A poppy-red blanket on the bed, embroidered linens, hand-painted prints. Step out the screen door onto a private firepit area.',
    type: 'Cabin',
    sleeps: 4,
    beds: '1 Queen + 1 Queen Sofa',
    bath: 'Shared',
    price: 270,
    ext: 'assets/mexico-ext.jpeg',
    int: 'assets/mexico-int.jpeg',
    features: ['Themed interior', 'Covered porch', 'Private firepit area', 'Full kitchen', 'Large wood-burning fireplace'],
  },
  {
    id: 'love-shack',
    name: 'The Love Shack',
    eyebrow: 'Romantic Suite',
    tag: 'Two adirondacks, gerberas on the table, a fir door.',
    blurb: 'For the people who came here for one reason. A raised king bed by the wood stove, low light, and absolutely zero kid-friendliness.',
    type: 'Couples',
    sleeps: 2,
    beds: '1 Raised King',
    bath: 'Shared',
    price: 185,
    ext: 'assets/love-shack-new.jpeg',
    int: 'assets/love-shack-new.jpeg',
    features: ['Raised king bed', 'Wood-burning fireplace', 'Adults only', 'Full kitchen', 'Private deck'],
  },
  {
    id: 'library',
    name: 'The Library',
    eyebrow: "Reader's Paradise",
    tag: 'Hundreds of stories. One couch. Pages turning.',
    blurb: 'A whole cabin built around the books. Real shelves, real pages, real silence except for the wood-burning fireplace and your own breathing. Sleeps three: one queen, one child pull-out.',
    type: 'Cabin',
    sleeps: 3,
    beds: '1 Queen + 1 Child Pull-out',
    bath: 'Shared',
    price: 225,
    ext: 'assets/library-ext.jpeg',
    int: 'assets/library-int.jpeg',
    features: ['Extensive book collection', 'Wood-burning fireplace', 'Full kitchen', 'Large private deck', 'Wood floors'],
  },
  {
    id: 'chapel',
    name: 'The Chapel',
    tag: 'Vaulted ceiling. Tall window. Forest cathedral.',
    blurb: 'A cathedral window looking straight into the trees. The quietest cabin we have, set deepest in the cedars.',
    type: 'Cabin',
    sleeps: 4,
    beds: '1 Queen',
    bath: 'Private',
    price: 400,
    ext: 'assets/chapel-ext.jpeg',
    int: 'assets/chapel-int.jpeg',
    features: ['Cathedral window', 'Vaulted ceiling', 'Forest setting', 'Private bath'],
  },
  {
    id: 'bunkhouse',
    name: 'The Bunk House',
    eyebrow: 'The Group Hub',
    tag: 'The hangout. The largest kitchen. The bar. The crew lives here.',
    blurb: 'Built for the wedding party, the family reunion, the crew that wants the whole hangout under one roof. The largest kitchen on the property, a bar built in, room for eight across two queens, a double pull-out, and two loft twins. The default first choice for a multi-cabin booking, and the wedding-party HQ during any full-resort weekend. No woodstove in this one — intentional. It stays warm differently.',
    type: 'Group',
    sleeps: 8,
    beds: '2 Queens + 1 Double Pull-out + 2 Loft Twins',
    bath: 'Shared',
    price: 325,
    ext: 'assets/bunkhouse-ext.jpeg',
    int: 'assets/bunkhouse-int.jpeg',
    features: ['Full kitchen + bar area', 'Electric / propane heating', 'Sleeps 8'],
  },
  {
    id: 'glamping-1',
    name: 'Glamping — Plaid',
    tag: 'Bell tent. Buffalo plaid. String lights.',
    blurb: 'Two real beds, plaid throws, candles on the trunk. Halfway between camping and a small hotel.',
    type: 'Glamping',
    sleeps: 2,
    beds: '2 Twins',
    bath: 'Shared bathhouse',
    price: 175,
    ext: 'assets/glamping-tent-3.jpeg',
    int: 'assets/glamping-1.jpeg',
    features: ['Bell tent', 'Real beds', 'Solar lights', 'Bathhouse 30s away'],
  },
  {
    id: 'glamping-2',
    name: 'Glamping — Saffron',
    tag: 'Bell tent. Persian rug. Lanterns.',
    blurb: 'A saffron-toned tent with a tiled rug, striped cushions, and lanterns on the dressers.',
    type: 'Glamping',
    sleeps: 2,
    beds: '2 Twins',
    bath: 'Shared bathhouse',
    price: 175,
    ext: 'assets/glamping-tent-4.jpeg',
    int: 'assets/glamping-2.jpeg',
    features: ['Bell tent', 'Real beds', 'Solar lights', 'Bathhouse 30s away'],
  },];

window.AREA = [
  { num: '01', name: 'Gates Lake Dock', dist: 'On site',  desc: 'Jump off it. Read on it. Watch a heron miss a fish from it.' },
  { num: '02', name: 'Birkenhead Provincial Park', dist: '6 min drive', desc: 'Old-growth fir, swimming holes, a beach that\'s never crowded.' },
  { num: '03', name: 'Pemberton Farmer\'s Market', dist: '22 min drive', desc: 'Saturday mornings. Cheese, jam, sourdough, the dog comes too.' },
  { num: '04', name: 'Joffre Lakes', dist: '40 min drive', desc: 'The famous turquoise three. Yes, it\'s as cold as it looks.' },
  { num: '05', name: 'Whistler Village', dist: '55 min drive', desc: 'When you want a chairlift, a brewery and a different planet for an afternoon.' },
  { num: '06', name: 'Lillooet', dist: '1 hr drive',  desc: 'Cowboy country. Sage, sandstone, the dry side of the mountains.' },
];

window.MENU = {
  starters: [
    { name: 'Cedar-plank Salmon Bites', price: '18', desc: 'Maple, mustard, lemon. Smoke off the grill.' },
    { name: 'Campfire Cornbread', price: '11', desc: 'Iron skillet, honey butter, flake salt.' },
    { name: 'Pickled Things', price: '9',  desc: 'Whatever the garden gave us this week.' },
    { name: 'Smokehouse Wings', price: '17', desc: 'Hot, sticky, six napkins minimum.' },
  ],
  mains: [
    { name: 'The Grille Burger', price: '22', desc: 'Local beef, cheddar, secret sauce, sesame brioche, fries.' },
    { name: 'Trout in Brown Butter', price: '32', desc: 'Whole rainbow trout, lemon, capers, parsley.' },
    { name: 'Wood-fired Mushroom Pizza', price: '24', desc: 'Cremini, taleggio, thyme, hot honey.' },
    { name: 'Birken Steak Frites', price: '36', desc: '10oz ribeye, garlic butter, hand-cut fries, watercress.' },
  ],
  drinks: [
    { name: 'Cold Beer',     price: '7',  desc: 'Whatever\'s in the fridge. Local.' },
    { name: 'Smoked Old Fashioned', price: '15', desc: 'Bourbon, cedar smoke, orange peel.' },
    { name: 'Lake Water',    price: '0',  desc: 'Filtered. Free. Always.' },
    { name: 'Hot Toddy',     price: '11', desc: 'For the porch when the sun goes down.' },
  ],
};
