/* Cabin data — Birken Lakeside Resort */
window.CABINS = [
  {
    id: 'wild-west',
    name: 'Wild West',
    tag: 'Historic log cabin. Lakeside.',
    blurb: 'A real 1906 log cabin on the lake. Wood stove, planked floors, kettle on the boil. The oldest soul on the property.',
    type: 'Cabin',
    sleeps: 4,
    beds: '1 Queen + 1 Sofa',
    bath: 'Private',
    price: 285,
    ext: 'assets/wildwest-ext.jpeg',
    int: 'assets/wildwest-int.jpeg',
    features: ['Wood stove', 'Lake view', 'Full kitchen', 'Original 1906 logs', 'Front porch', 'Pet friendly'],
  },
  {
    id: 'morocco',
    name: 'Morocco',
    tag: 'Lanterns, leopard-print.',
    blurb: 'Brass lanterns, woven headboard, a hookah on the side table you don\'t have to use. The smallest cabin with the loudest personality.',
    type: 'Cabin',
    sleeps: 2,
    beds: '1 Queen',
    bath: 'Shared',
    price: 215,
    ext: 'assets/morocco-cabin-night.jpeg',
    int: 'assets/morocco-lantern.jpeg',
    features: ['Themed interior', 'Reading nook', 'Mini fridge', 'Covered porch'],
  },
  {
    id: 'mexico',
    name: 'Mexico',
    tag: 'Spanish tile, scarlet blanket, courtyard porch.',
    blurb: 'A poppy-red blanket on the bed, embroidered linens, hand-painted prints. Step out the screen door onto a stone courtyard.',
    type: 'Cabin',
    sleeps: 2,
    beds: '1 Queen',
    bath: 'Shared',
    price: 215,
    ext: 'assets/mexico-ext.jpeg',
    int: 'assets/mexico-int.jpeg',
    features: ['Themed interior', 'Stone courtyard', 'Mini fridge', 'Wood stove'],
  },
  {
    id: 'love-shack',
    name: 'The Love Shack',
    tag: 'Raised king. Heart-shaped pillows. No regrets.',
    blurb: 'For the people who came here for one reason. A raised king bed by the wood stove, low light, and absolutely zero kid-friendliness.',
    type: 'Couples',
    sleeps: 2,
    beds: '1 King',
    bath: 'Private',
    price: 325,
    ext: 'assets/love-shack-new.jpeg',
    int: 'assets/love-shack-new.jpeg',
    features: ['Raised king bed', 'Wood stove', 'Adults only', 'Kitchenette', 'Private deck'],
  },
  {
    id: 'library',
    name: 'The Library',
    tag: 'Hundreds of lines. One armchair. Pages turning.',
    blurb: 'A whole cabin built around the books. Real shelves, real pages, real silence except for the wood stove and your own breathing. Sleeps two: one queen, one small single pullout.',
    type: 'Cabin',
    sleeps: 2,
    beds: '1 Queen + 1 Small Single Pullout',
    bath: 'Private',
    price: 245,
    ext: 'assets/library-ext.jpeg',
    int: 'assets/library-int.jpeg',
    features: ['Built-in library', 'Wood stove', 'Reading deck', 'Wood floors'],
  },
  {
    id: 'chapel',
    name: 'The Chapel',
    tag: 'Vaulted ceiling. Tall window. Forest cathedral.',
    blurb: 'A cathedral window looking straight into the trees. The quietest cabin we have, set deepest in the cedars.',
    type: 'Cabin',
    sleeps: 4,
    beds: '1 Queen',
    bath: 'Private',
    price: 265,
    ext: 'assets/chapel-ext.jpeg',
    int: 'assets/chapel-int.jpeg',
    features: ['Cathedral window', 'Vaulted ceiling', 'Forest setting', 'Private bath'],
  },
  {
    id: 'bunkhouse',
    name: 'The Bunkhouse',
    tag: 'The group hub. Foosball, fireplace, foosball.',
    blurb: 'The heart of any group booking. Couches, foosball, a piano nobody can play, and room for everyone to land somewhere soft.',
    type: 'Group',
    sleeps: 8,
    beds: 'Various',
    bath: '2 baths',
    price: 685,
    ext: 'assets/bunkhouse-ext.jpeg',
    int: 'assets/bunkhouse-int.jpeg',
    features: ['Foosball + piano', 'Wood stove', 'TV / record player', 'Sleeps 8', 'Group hub'],
  },
  {
    id: 'glamping-1',
    name: 'Glamping — Plaid',
    tag: 'Bell tent. Buffalo plaid. String lights.',
    blurb: 'Two real beds, plaid throws, candles on the trunk. Halfway between camping and a small hotel.',
    type: 'Glamping',
    sleeps: 2,
    beds: '2 Twins',
    bath: 'Shared bathhouse',
    price: 165,
    ext: 'assets/glamping-1.jpeg',
    int: 'assets/glamping-1.jpeg',
    features: ['Bell tent', 'Real beds', 'Solar lights', 'Bathhouse 30s away'],
  },
  {
    id: 'glamping-2',
    name: 'Glamping — Saffron',
    tag: 'Bell tent. Persian rug. Lanterns.',
    blurb: 'A saffron-toned tent with a tiled rug, striped cushions, and lanterns on the dressers.',
    type: 'Glamping',
    sleeps: 2,
    beds: '2 Twins',
    bath: 'Shared bathhouse',
    price: 165,
    ext: 'assets/glamping-2.jpeg',
    int: 'assets/glamping-2.jpeg',
    features: ['Bell tent', 'Real beds', 'Solar lights', 'Bathhouse 30s away'],
  },];

window.AREA = [
  { num: '01', name: 'Gates Lake Dock', dist: 'On site',  desc: 'Jump off it. Read on it. Watch a heron miss a fish from it.' },
  { num: '02', name: 'Birkenhead Provincial Park', dist: '6 min drive', desc: 'Old-growth cedar, swimming holes, a beach that\'s never crowded.' },
  { num: '03', name: 'Pemberton Farmer\'s Market', dist: '22 min drive', desc: 'Saturday mornings. Cheese, jam, sourdough, the dog comes too.' },
  { num: '04', name: 'Joffre Lakes', dist: '40 min drive', desc: 'The famous turquoise three. Yes, it\'s as cold as it looks.' },
  { num: '05', name: 'Whistler Village', dist: '55 min drive', desc: 'When you want a chairlift, a brewery and a different planet for an afternoon.' },
  { num: '06', name: 'Lillooet', dist: '1 hr drive',  desc: 'Cowboy country. Sage, sandstone, the dry side of the mountains.' },
];

window.MENU = {
  starters: [
    { name: 'Cedar-plank Salmon Bites', price: '18', desc: 'Maple, mustard, lemon. Smoke off the grill.' },
    { name: 'Campfire Cornbread', price: '11', desc: 'Iron skillet, honey butter, flake salt.' },
    { name: 'Pickled Things', price: '9',  desc: 'Whatever the garden gave us this week.' },
    { name: 'Smokehouse Wings', price: '17', desc: 'Hot, sticky, six napkins minimum.' },
  ],
  mains: [
    { name: 'The Grille Burger', price: '22', desc: 'Local beef, cheddar, secret sauce, sesame brioche, fries.' },
    { name: 'Trout in Brown Butter', price: '32', desc: 'Whole rainbow trout, lemon, capers, parsley.' },
    { name: 'Wood-fired Mushroom Pizza', price: '24', desc: 'Cremini, taleggio, thyme, hot honey.' },
    { name: 'Birken Steak Frites', price: '36', desc: '10oz ribeye, garlic butter, hand-cut fries, watercress.' },
  ],
  drinks: [
    { name: 'Cold Beer',     price: '7',  desc: 'Whatever\'s in the fridge. Local.' },
    { name: 'Smoked Old Fashioned', price: '15', desc: 'Bourbon, cedar smoke, orange peel.' },
    { name: 'Lake Water',    price: '0',  desc: 'Filtered. Free. Always.' },
    { name: 'Hot Toddy',     price: '11', desc: 'For the porch when the sun goes down.' },
  ],
};
